import { useEffect, useMemo, useState } from 'react'
import { downloadExcelReport } from './exportExcel'
import * as XLSX from 'xlsx'
import './App.css'

const breakdownFields = [['it', 'IT Breakdown'], ['tsi', 'TS&I Breakdown'], ['pqmi', 'PQMI'], ['ir', 'IR'], ['pe', 'PE'], ['ppc', 'PPC'], ['co', 'C/O'], ['qa', 'QA Issue'], ['npi', 'NPI']]
const blankRow = (date) => ({ date, line: '', shift: 'A', hour: '', runMinutes: 60, customer: '', model: '', lCode: '', ieUph: '', ppcPlan: '', actual: '', planUph: '', reasonCategory: '', lossFrom: '', lossTo: '', lossMinutes: 0, reason: '', rootCause: '', action: '', other: '', it: 0, tsi: 0, pqmi: 0, ir: 0, pe: 0, ppc: 0, co: 0, qa: 0, npi: 0 })
const numberValue = (value) => Number(value) || 0
const hourOptions = Array.from({ length: 24 }, (_, hour) => `${String(hour).padStart(2, '0')}:00`)
const signedValue = (value) => value > 0 ? `+${value}` : String(value)
const hourRange = (hour) => { if (!hour) return '-'; const nextHour = `${String((Number(hour.slice(0, 2)) + 1) % 24).padStart(2, '0')}:00`; return `${hour}-${nextHour}` }
const timeDifference = (from, to) => { if (!from || !to) return 0; const start = Number(from.slice(0, 2)) * 60 + Number(from.slice(3, 5)); const end = Number(to.slice(0, 2)) * 60 + Number(to.slice(3, 5)); return end >= start ? end - start : (24 * 60) - start + end }
const normalizeTimeInput = (value) => { const digits = value.replace(/\D/g, '').slice(0, 4); return digits.length > 2 ? `${digits.slice(0, 2)}:${digits.slice(2)}` : digits }
const isValidTime = (value) => /^(?:[01]\d|2[0-3]):[0-5]\d$/.test(value)
const blankLoss = () => ({ reasonCategory: '', lossFrom: '', lossTo: '', reason: '', rootCause: '', action: '' })
const emptyContext = { date: '', line: '', shift: 'A', customer: '', model: '', lCode: '', planUph: '', ieUph: '' }
const lossCategories = [...breakdownFields.map(([, label]) => label), 'Machine (L-Code)', 'Other']
const normalizeShift = (value) => ({ '1- Pack Size': 'A', '2- Camera': 'B', '3- Assembly': 'C', General: 'A' }[String(value)] || String(value || 'A'))
const loadSavedContext = () => { try { const saved = JSON.parse(localStorage.getItem('daily-production-context') || 'null'); return saved ? { ...emptyContext, ...saved, shift: normalizeShift(saved.shift) } : emptyContext } catch { return emptyContext } }
const isCompleteLoss = (loss) => Boolean(loss?.reasonCategory && isValidTime(loss.lossFrom) && isValidTime(loss.lossTo) && loss?.reason?.trim())
const loadSavedRows = () => { try { const saved = JSON.parse(localStorage.getItem('daily-production-hourly-rows') || '[]'); return saved.map((row) => ({ ...row, shift: normalizeShift(row.shift), lossLogs: (row.lossLogs || []).filter(isCompleteLoss) })) } catch { return [] } }
function App() {
  const [reportContext, setReportContext] = useState(loadSavedContext)
  const [reportDate, setReportDate] = useState(() => reportContext.date)
  const [rows, setRows] = useState(loadSavedRows)
  const [downloaded, setDownloaded] = useState(false)
  const [importMessage, setImportMessage] = useState('')
  const [entry, setEntry] = useState({ ...blankRow(reportContext.date), lossLogs: [blankLoss()] })
  const totals = useMemo(() => rows.reduce((result, row) => { result.plan += numberValue(row.ppcPlan); result.actual += numberValue(row.actual); result.breakdown += breakdownFields.reduce((sum, [key]) => sum + numberValue(row[key]), 0); return result }, { plan: 0, actual: 0, breakdown: 0 }), [rows])
  const categoryLosses = useMemo(() => lossCategories.map((category) => rows.reduce((result, row) => { const losses = row.lossLogs?.length ? row.lossLogs : [{ reasonCategory: row.reasonCategory, lossMinutes: row.lossMinutes }]; losses.forEach((lossEntry) => { if ((lossEntry.reasonCategory || 'Other') === category) result.minutes += numberValue(lossEntry.lossMinutes) }); return result }, { category, minutes: 0 })), [rows])
  useEffect(() => { localStorage.setItem('daily-production-context', JSON.stringify(reportContext)); localStorage.setItem('daily-production-hourly-rows', JSON.stringify(rows)) }, [reportContext, rows])
  const updateRow = (index, field, value) => { setRows((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, [field]: value } : row)); setDownloaded(false) }
  const removeRow = (index) => { setRows((current) => current.filter((_, rowIndex) => rowIndex !== index)); setImportMessage('Hourly entry and linked breakdown removed') }
  const clearBreakdown = (index) => { setRows((current) => current.map((row, rowIndex) => { if (rowIndex !== index) return row; const clearedMinutes = Object.fromEntries(breakdownFields.map(([key]) => [key, 0])); return { ...row, ...clearedMinutes, lossLogs: [], reasonCategory: '', lossFrom: '', lossTo: '', lossMinutes: 0, reason: '', rootCause: '', action: '', other: '' } })); setImportMessage('Breakdown data removed; production entry kept') }
  const removeBreakdownLoss = (rowIndex, lossIndex) => { setRows((current) => current.map((row, index) => { if (index !== rowIndex) return row; const lossLogs = (row.lossLogs || []).filter((_, indexInLosses) => indexInLosses !== lossIndex); return { ...row, lossLogs, reason: lossLogs.map((loss) => `${loss.reasonCategory}: ${loss.reason} (${loss.lossFrom}-${loss.lossTo}, ${loss.lossMinutes} min)`).join('\n'), lossMinutes: lossLogs.reduce((sum, loss) => sum + numberValue(loss.lossMinutes), 0) } })); setImportMessage('Breakdown reason removed') }
  const addEntry = (event) => {
    event.preventDefault()
    if (!reportContext.date || !reportContext.line || !reportContext.customer || !reportContext.model || reportContext.planUph === '' || entry.actual === '') { window.alert('Complete Date, Line, Customer, Model, Plan UPH and Actual Parts before saving'); return }
    if (!isValidTime(entry.hour)) { window.alert('Enter a valid Hour Time in HH:MM format, for example 09:00'); return }
    const hasInvalidLoss = entry.lossLogs.some((loss) => (loss.reasonCategory || loss.lossFrom || loss.lossTo || loss.reason.trim()) && !isCompleteLoss(loss))
    if (hasInvalidLoss) { window.alert('Complete each loss with category, valid HH:MM times and reason'); return }
    const plannedParts = Math.round((numberValue(entry.runMinutes) / 60) * numberValue(reportContext.planUph))
    const lossLogs = entry.lossLogs.filter(isCompleteLoss).map((loss) => ({ ...loss, lossMinutes: timeDifference(loss.lossFrom, loss.lossTo) }))
    const firstLoss = lossLogs[0] || blankLoss()
    const combinedReason = lossLogs.map((loss) => `${loss.reasonCategory}: ${loss.reason} (${loss.lossFrom}-${loss.lossTo}, ${loss.lossMinutes} min)`).join('\n')
    setRows((current) => [...current, { ...entry, ...reportContext, date: reportContext.date, ppcPlan: plannedParts, planUph: reportContext.planUph, reasonCategory: firstLoss.reasonCategory, lossFrom: firstLoss.lossFrom, lossTo: firstLoss.lossTo, reason: combinedReason, lossMinutes: lossLogs.reduce((sum, loss) => sum + loss.lossMinutes, 0), lossLogs }])
    setEntry({ ...blankRow(reportContext.date), lossLogs: [blankLoss()] })
    setImportMessage('This hour was added to Shift Output')
  }
  const updateEntry = (field, value) => setEntry((current) => ({ ...current, [field]: value }))
  const updateLoss = (index, field, value) => setEntry((current) => ({ ...current, lossLogs: current.lossLogs.map((loss, lossIndex) => lossIndex === index ? { ...loss, [field]: value } : loss) }))
  const updateBreakdownField = (rowIndex, lossIndex, field, value) => setRows((current) => current.map((row, index) => { if (index !== rowIndex) return row; const lossLogs = (row.lossLogs || []).map((loss, indexInLosses) => indexInLosses === lossIndex ? { ...loss, [field]: value } : loss); return { ...row, lossLogs, [field]: lossLogs.map((loss) => loss[field]).filter(Boolean).join('\n') } }))
  const addLoss = () => setEntry((current) => ({ ...current, lossLogs: [...current.lossLogs, blankLoss()] }))
  const removeLoss = (index) => setEntry((current) => ({ ...current, lossLogs: current.lossLogs.filter((_, lossIndex) => lossIndex !== index) }))
  const expectedHourlyParts = Math.round((numberValue(entry.runMinutes) / 60) * numberValue(reportContext.planUph))
  const hourlyGap = numberValue(entry.actual) - expectedHourlyParts
  const breakdownRows = rows.flatMap((row, rowIndex) => { const losses = (row.lossLogs || []).filter(isCompleteLoss); if (losses.length) return losses.map((loss, lossIndex) => ({ row: { ...row, reason: loss.reason, lossFrom: loss.lossFrom, lossTo: loss.lossTo, lossMinutes: loss.lossMinutes, rootCause: loss.rootCause || '', action: loss.action || '' }, rowIndex, lossIndex })); return row.reason || row.rootCause || row.action ? [{ row, rowIndex, lossIndex: null }] : [] })
  const saveContext = (event) => { event.preventDefault(); setReportDate(reportContext.date); setEntry({ ...blankRow(reportContext.date), lossLogs: [blankLoss()] }); setImportMessage('Report details saved. Now add hourly entries.') }
  const updateContext = (field, value) => setReportContext((current) => ({ ...current, [field]: value }))

  const downloadReport = () => {
    downloadExcelReport({ rows, totals, categoryLosses, breakdownFields, numberValue, timeDifference, reportDate })
    setRows([])
    setReportContext(emptyContext)
    setReportDate('')
    setEntry({ ...blankRow(''), lossLogs: [blankLoss()] })
    setDownloaded(true)
    setImportMessage('Excel downloaded. Form cleared for the next report.')
  }

  const _legacyDownloadReport = () => {
    const headers = ['Date', 'Line', 'Customer', 'Model', 'IE UPH', 'Shift', 'Available Time (Hr.)', 'PPC Plan', 'Actual Quantity', 'Gap/Excess', 'Ach %', 'Plan UPH', 'Actual UPH', 'L-Code', ...breakdownFields.map(([, label]) => label), 'Other', 'Total B/D Min.', 'Loss in Pcs', 'Reason', 'Root Cause', 'Action']
    const categoryTotals = categoryLosses.map(({ category, minutes }) => [category, minutes])
    const data = rows.map((row) => { const totalBreakdown = breakdownFields.reduce((sum, [key]) => sum + numberValue(row[key]), 0); const actual = numberValue(row.actual); const plan = numberValue(row.ppcPlan); const runMinutes = numberValue(row.runMinutes); const actualUph = runMinutes ? Math.round((actual * 60) / runMinutes) : 0; const losses = row.lossLogs?.length ? row.lossLogs : [{ reasonCategory: row.reasonCategory, lossFrom: row.lossFrom, lossTo: row.lossTo, lossMinutes: row.lossMinutes, reason: row.reason, rootCause: row.rootCause, action: row.action }]; const reason = losses.filter((loss) => loss.reasonCategory || loss.reason).map((loss) => `${loss.reasonCategory ? `${loss.reasonCategory}: ` : ''}${loss.reason || ''}${loss.lossFrom && loss.lossTo ? ` (${loss.lossFrom}-${loss.lossTo}, ${loss.lossMinutes || timeDifference(loss.lossFrom, loss.lossTo)} min)` : ''}`).join('\n'); const rootCause = losses.map((loss) => loss.rootCause).filter(Boolean).join('\n'); const action = losses.map((loss) => loss.action).filter(Boolean).join('\n'); return [row.date, row.line, row.customer, row.model, numberValue(row.ieUph), row.shift, numberValue(row.runMinutes) / 60, plan, actual, actual - plan, plan ? actual / plan : 0, Math.round(numberValue(row.planUph)), actualUph, row.lCode, ...breakdownFields.map(([key]) => numberValue(row[key])), numberValue(row.other), totalBreakdown, numberValue(row.ieUph) ? (totalBreakdown * 60) / numberValue(row.ieUph) : 0, reason, rootCause, action] })
    const totalRow = ['TOTAL', '', '', '', '', '', '', totals.plan, totals.actual, totals.actual - totals.plan, totals.plan ? totals.actual / totals.plan : 0, '', '', '', ...breakdownFields.map(([key]) => rows.reduce((sum, row) => sum + numberValue(row[key]), 0)), rows.reduce((sum, row) => sum + numberValue(row.other), 0), rows.reduce((sum, row) => sum + breakdownFields.reduce((value, [key]) => value + numberValue(row[key]), 0), 0), categoryTotals.reduce((sum, [, minutes]) => sum + minutes, 0), 'Category-wise loss minutes are listed below', '', '']
    const categoryRows = categoryTotals.map(([category, minutes]) => [category, minutes, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', `${minutes} min loss`, '', ''])
    const sheet = XLSX.utils.aoa_to_sheet([['PRODUCTION - NOTEBOOK', ...Array(headers.length - 1).fill('')], ['DAILY PRODUCTION REPORT', ...Array(headers.length - 1).fill('')], headers, ...data, totalRow, ['CATEGORY-WISE LOSS TOTALS', ...Array(headers.length - 1).fill('')], ...categoryRows])
    const headerRow = 2; const dataStart = 3; const totalRowIndex = dataStart + data.length
    sheet['!merges'] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: 12 } }, { s: { r: 1, c: 0 }, e: { r: 1, c: headers.length - 1 } }, { s: { r: totalRowIndex + 1, c: 0 }, e: { r: totalRowIndex + 1, c: headers.length - 1 } }]
    sheet['!cols'] = headers.map((header, index) => ({ wch: index >= 21 ? 28 : index >= 14 ? 11 : Math.max(10, Math.min(16, header.length + 2)) })); sheet['!rows'] = [{ hpt: 27 }, { hpt: 27 }, { hpt: 34 }, ...data.map(() => ({ hpt: 58 })), { hpt: 24 }]; sheet['!freeze'] = { xSplit: 2, ySplit: 3 }
    const border = { top: { style: 'thin', color: { rgb: '808080' } }, bottom: { style: 'thin', color: { rgb: '808080' } }, left: { style: 'thin', color: { rgb: '808080' } }, right: { style: 'thin', color: { rgb: '808080' } } }
    const setStyle = (cell, fill, color = '000000', bold = false, align = 'center') => { if (!cell) return; cell.s = { fill: { patternType: 'solid', fgColor: { rgb: fill } }, font: { name: 'Arial', sz: 8, bold, color: { rgb: color } }, alignment: { horizontal: align, vertical: 'center', wrapText: true }, border } }
    for (let column = 0; column < headers.length; column += 1) { setStyle(sheet[XLSX.utils.encode_cell({ r: 0, c: column })], 'FFFFFF', '000000', true); setStyle(sheet[XLSX.utils.encode_cell({ r: 1, c: column })], 'FFFFFF', '000000', true); setStyle(sheet[XLSX.utils.encode_cell({ r: headerRow, c: column })], column >= 13 && column <= 24 ? 'FF0000' : '5B9BD5', 'FFFFFF', true) }
    for (let rowIndex = dataStart; rowIndex <= totalRowIndex; rowIndex += 1) for (let column = 0; column < headers.length; column += 1) setStyle(sheet[XLSX.utils.encode_cell({ r: rowIndex, c: column })], rowIndex === totalRowIndex ? 'D9EAD3' : 'FFFFFF', '000000', rowIndex === totalRowIndex, column >= 21 ? 'left' : 'center')
    for (let rowIndex = totalRowIndex + 1; rowIndex < totalRowIndex + 2 + categoryRows.length; rowIndex += 1) for (let column = 0; column < headers.length; column += 1) setStyle(sheet[XLSX.utils.encode_cell({ r: rowIndex, c: column })], rowIndex === totalRowIndex + 1 ? '5B9BD5' : 'FFFFFF', rowIndex === totalRowIndex + 1 ? 'FFFFFF' : '000000', true, column === 0 ? 'left' : 'center')
    for (let rowIndex = dataStart; rowIndex <= totalRowIndex; rowIndex += 1) { const achievementCell = sheet[XLSX.utils.encode_cell({ r: rowIndex, c: 10 })]; if (achievementCell) achievementCell.z = '0.00%' }
    const exportedRows = XLSX.utils.sheet_to_json(sheet, { header: 1, raw: true })
    const escapeHtml = (value) => String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
    const htmlRows = exportedRows.map((row, rowIndex) => { const isTitle = rowIndex < 2; const isHeader = rowIndex === headerRow; const isTotal = rowIndex === totalRowIndex; const isCategoryTitle = rowIndex === totalRowIndex + 1; const cells = row.map((value, column) => { const fill = isHeader || isCategoryTitle ? (isHeader && column >= 13 && column <= 24 ? '#ff0000' : '#5b9bd5') : isTotal ? '#d9ead3' : '#ffffff'; const weight = isTitle || isHeader || isTotal || isCategoryTitle ? 'bold' : 'normal'; const align = column >= 21 ? 'left' : 'center'; return `<td style="border:1px solid #808080;background:${fill};font-weight:${weight};text-align:${align};vertical-align:middle;white-space:pre-wrap;">${escapeHtml(value)}</td>` }).join(''); return `<tr style="height:${isTitle ? 27 : isHeader ? 34 : 58}px">${cells}</tr>` }).join('')
    const html = `<html><head><meta charset="utf-8"><style>body{font-family:Arial;font-size:8pt}table{border-collapse:collapse}td{padding:4px;min-width:55px}tr:first-child td,tr:nth-child(2) td{font-size:15pt;height:27px}tr:nth-child(2) td{text-align:center}</style></head><body><table>${htmlRows}</table></body></html>`
    const downloadUrl = URL.createObjectURL(new Blob([html], { type: 'application/vnd.ms-excel' })); const downloadLink = document.createElement('a'); downloadLink.href = downloadUrl; downloadLink.download = `Daily-Production-Report-${reportDate}.xls`; downloadLink.click(); URL.revokeObjectURL(downloadUrl)
    setRows([])
    setReportContext(emptyContext)
    setReportDate('')
    setEntry({ ...blankRow(''), lossLogs: [blankLoss()] })
    setDownloaded(true)
    setImportMessage('Excel downloaded. Form cleared for the next report.')
  }

  return <main className="app-shell"><details className="multi-loss-panel"><summary className="loss-log-toggle">+ Add loss reason</summary><div className="loss-log-heading">LOSS REASON LOG <small>Add one or more losses for this hour</small></div>{entry.lossLogs.map((loss, lossIndex) => <div className="loss-entry" key={`loss-${lossIndex}`}><label>BREAKDOWN CATEGORY<select value={loss.reasonCategory} onChange={(event) => updateLoss(lossIndex, 'reasonCategory', event.target.value)}><option value="">Select category</option>{breakdownFields.map(([, label]) => <option key={label}>{label}</option>)}<option>Machine (L-Code)</option><option>Other</option></select></label><label>LOSS FROM<input type="text" inputMode="numeric" placeholder="HH:MM" value={loss.lossFrom} onChange={(event) => updateLoss(lossIndex, 'lossFrom', normalizeTimeInput(event.target.value))} /></label><label>LOSS TO<input type="text" inputMode="numeric" placeholder="HH:MM" value={loss.lossTo} onChange={(event) => updateLoss(lossIndex, 'lossTo', normalizeTimeInput(event.target.value))} /></label><strong className="loss-minutes">{timeDifference(loss.lossFrom, loss.lossTo)} min</strong><label className="reason-field">REASON<textarea value={loss.reason} placeholder="Machine stopped, sensor issue..." onChange={(event) => updateLoss(lossIndex, 'reason', event.target.value)} /></label>{entry.lossLogs.length > 1 && <button className="remove-loss" type="button" onClick={() => removeLoss(lossIndex)}>Remove</button>}</div>)}<button className="add-loss" type="button" onClick={addLoss}>+ Add another loss</button></details>
    <header className="topbar"><div className="brand"><span className="brand-mark">▦</span><div><strong>Notebook</strong><span>Production control</span></div></div><div className="header-actions"><button className="download-button" type="button" onClick={downloadReport}><span>↓</span> Download Excel</button></div></header>
    <section className="intro"><div><p className="eyebrow">DAILY PRODUCTION REPORT / 01</p><h1>Make the shift<br /><em>visible.</em></h1><p className="intro-copy">Capture line performance, losses, and action notes in one clean report.</p>{importMessage && <p className="import-message">{importMessage}</p>}</div><div className="status-note"><span className="live-dot" /> Draft report <strong>{reportDate}</strong><small>{downloaded ? 'Excel downloaded' : 'Ready to export'}</small></div></section>
    <section className="context-section"><div className="section-heading"><div><p className="eyebrow">01 / REPORT SETUP</p><h2>Save report details once</h2></div><span className="section-hint">These details stay saved for every next hour</span></div><form className="context-form" onSubmit={saveContext}><label>DATE<input type="date" value={reportContext.date} onChange={(event) => updateContext('date', event.target.value)} required /></label><label>LINE<select value={reportContext.line} onChange={(event) => updateContext('line', event.target.value)} required><option value="">Select line</option><option>NB01</option><option>NB02</option><option>NB03</option></select></label><label>SHIFT<select value={reportContext.shift} onChange={(event) => updateContext('shift', event.target.value)}><option>A</option><option>B</option><option>C</option><option>D1</option><option>D2</option></select></label><label>CUSTOMER<input value={reportContext.customer} onChange={(event) => updateContext('customer', event.target.value)} required /></label><label>MODEL<input value={reportContext.model} onChange={(event) => updateContext('model', event.target.value)} required /></label><label>PLAN UPH<input type="number" min="0" value={reportContext.planUph} onChange={(event) => updateContext('planUph', event.target.value)} required /></label><label>IE UPH<input type="number" min="0" step="0.01" value={reportContext.ieUph} onChange={(event) => updateContext('ieUph', event.target.value)} /></label><button className="save-context-button" type="submit">Save report details</button></form></section>
    <section className="summary-grid"><div className="summary-card"><span>PLANNED PCS</span><strong>{totals.plan.toLocaleString()}</strong><small>Across {rows.length} hourly entries</small></div><div className="summary-card actual"><span>ACTUAL PCS</span><strong>{totals.actual.toLocaleString()}</strong><small className={totals.actual >= totals.plan ? 'positive' : 'negative'}>{totals.plan ? `${((totals.actual / totals.plan) * 100).toFixed(1)}% achievement` : '0% achievement'}</small></div><div className="summary-card"><span>EXCESS / LOSS PCS</span><strong>{signedValue(totals.actual - totals.plan)}</strong><small>+ excess / - loss</small></div><div className="summary-card accent"><span>HOURS ENTERED</span><strong>{String(rows.length).padStart(2, '0')}</strong><small>Hourly entries saved</small></div></section>
    <section className="entry-section"><div className="section-heading"><div><p className="eyebrow">02 / HOURLY PRODUCTION</p><h2>Record this hour</h2></div><span className="section-hint">Saved details: {reportContext.customer || 'complete report setup first'} / {reportContext.model || 'model'}</span></div><form className="entry-form" onSubmit={addEntry}><label>HOUR / TIME<select value={entry.hour} onChange={(event) => updateEntry('hour', event.target.value)} required><option value="">Select hour</option>{hourOptions.map((hour) => <option key={hour}>{hour}</option>)}</select></label><label>LINE RUN MINUTES<input type="number" min="0" max="60" value={entry.runMinutes} onChange={(event) => updateEntry('runMinutes', event.target.value)} required /></label><label>EXPECTED PARTS<strong className="calculated-value">{expectedHourlyParts}</strong></label><label>ACTUAL PARTS<input type="number" min="0" value={entry.actual} onChange={(event) => updateEntry('actual', event.target.value)} required /></label><label>EXCESS / LOSS<strong className={`calculated-value ${hourlyGap < 0 ? 'loss-value' : 'excess-value'}`}>{signedValue(hourlyGap)}</strong></label><div className="loss-log-panel"><div className="loss-log-heading">LOSS REASON LOG <small>Enter the exact loss window</small></div><label>BREAKDOWN CATEGORY<select value={entry.reasonCategory} onChange={(event) => updateEntry('reasonCategory', event.target.value)}><option value="">Select category</option>{breakdownFields.map(([, label]) => <option key={label}>{label}</option>)}<option>Machine (L-Code)</option><option>Other</option></select></label><label>LOSS FROM<input type="text" inputMode="numeric" pattern="(?:[01][0-9]|2[0-3]):[0-5][0-9]" placeholder="HH:MM" value={entry.lossFrom} onChange={(event) => updateEntry('lossFrom', normalizeTimeInput(event.target.value))} /></label><label>LOSS TO<input type="text" inputMode="numeric" pattern="(?:[01][0-9]|2[0-3]):[0-5][0-9]" placeholder="HH:MM" value={entry.lossTo} onChange={(event) => updateEntry('lossTo', normalizeTimeInput(event.target.value))} /></label><strong className="loss-minutes">{timeDifference(entry.lossFrom, entry.lossTo)} min loss</strong><label className="reason-field">REASON / BREAKDOWN CAUSE<textarea value={entry.reason} placeholder="Example: Machine stopped, sensor issue, material issue" onChange={(event) => updateEntry('reason', event.target.value)} /></label></div><button className="add-entry-button" type="submit">+ Add to Shift Output</button></form></section>
    <section className="report-section"><div className="section-heading"><div><p className="eyebrow">01 / PRODUCTION LINES</p><h2>Shift output</h2></div><span className="section-hint">Read-only log · add entries from the hourly form</span></div><div className="table-wrap"><table><thead><tr><th>LINE / SHIFT</th><th>HOUR</th><th>CUSTOMER</th><th>MODEL</th><th>PPC PLAN</th><th>ACTUAL QTY</th><th>ACH %</th><th>PLAN UPH</th><th>ACTUAL UPH</th><th></th></tr></thead><tbody>{rows.map((row, index) => { const achievement = numberValue(row.ppcPlan) ? (numberValue(row.actual) / numberValue(row.ppcPlan)) * 100 : 0; const actualUph = numberValue(row.runMinutes) ? Math.round((numberValue(row.actual) * 60) / numberValue(row.runMinutes)) : 0; return <tr key={`${row.line}-${index}`}><td><strong>{row.line}</strong><small className="table-subtext">Shift {row.shift}</small></td><td><strong className="hour-range">{hourRange(row.hour)}</strong></td><td>{row.customer}</td><td>{row.model}</td><td>{numberValue(row.ppcPlan).toLocaleString()}</td><td>{numberValue(row.actual).toLocaleString()}</td><td><span className={`achievement ${achievement >= 100 ? 'good' : 'warn'}`}>{achievement.toFixed(1)}%</span></td><td>{Math.round(numberValue(row.planUph))}</td><td><strong>{actualUph}</strong></td><td><button className="delete-row" type="button" title="Delete line" onClick={() => removeRow(index)}>×</button></td></tr> })}</tbody></table></div></section>
    <section className="report-section detail-section"><div className="section-heading"><div><p className="eyebrow">02 / LOSS ANALYSIS</p><h2>Breakdown & action log</h2></div><span className="section-hint">One row per loss reason</span></div><div className="category-loss-summary"><div className="category-loss-title">CATEGORY-WISE LOSS · LIVE TOTAL</div>{categoryLosses.map(({ category, minutes }) => <div className="category-loss-item" key={category}><span>{category}</span><strong>{minutes} min</strong></div>)}</div><div className="detail-grid">{breakdownRows.map(({ row, rowIndex, lossIndex }, index) => <article className="detail-row" key={`detail-${rowIndex}-${lossIndex ?? 'action'}`}><div className="detail-identity"><span className="row-number">0{index + 1}</span><div><strong>{row.line} / {row.shift}</strong><small>{row.customer} · Model {row.model} · {hourRange(row.hour)}</small></div><button className="delete-log" type="button" title="Delete breakdown data" onClick={() => lossIndex === null ? clearBreakdown(rowIndex) : removeBreakdownLoss(rowIndex, lossIndex)}>Delete row</button></div><div className="loss-window-column"><span>LOSS WINDOW</span><strong>{row.lossFrom && row.lossTo ? `${row.lossFrom}-${row.lossTo}` : '-'}</strong><small>{row.lossMinutes ? `${row.lossMinutes} min` : '-'}</small></div><div className="notes-grid action-log-fields">{[['reason', 'REASON', 'Add reason'], ['rootCause', 'ROOT CAUSE', 'Add root cause'], ['action', 'ACTION', 'Add action']].map(([key, label, placeholder]) => <label key={key}><span>{label}</span><input value={row[key]} placeholder={placeholder} onChange={(event) => lossIndex === null ? updateRow(rowIndex, key, event.target.value) : updateBreakdownField(rowIndex, lossIndex, key, event.target.value)} /></label>)}</div></article>)}</div></section>
    <footer><span>Notebook / Daily production report</span><span>Excel columns match the standard line report template</span></footer>
  </main>
}

export default App
